component: user
service:
  port: 80
  containerPort: 8080

initContainers:
  parameters_pull:
    image: docker.io/rkalluru/d77-parameter-store-init-container-image
    imagePullPolicy: Always

containers:
  main:
    image: rkalluru/d77-user
    imagePullPolicy: Always

volumeMounts:
  - name: parameters
    mountPath: /parameters

