apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  selector:
    app: {{ .Values.component }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
