apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.component }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/{{ .Values.env }}-roboshop-eks-pod-role-for-{{ .Values.component }}-ssm
